name: SlimeTinker
author: Sefiraat
description: 黏液科技附加 黏液匠魂 繁體翻譯版.
main: io.github.sefiraat.slimetinker.SlimeTinker
website: https://github.com/Sefiraat/SlimeTinker
version: ${project.version}
api-version: 1.16
depend:
  - Slimefun
softdepend:
  - InfinityExpansion
  - SlimefunWarfare
  - DynaTech
  - LiteXpansion
  - TranscEndence
  - Networks
commands:
  slimetinker:
    description: /slimetinker
    usage: /slimetinker <sub>
    aliases: [ st, tinker ]
