name: SlimeTinker
author: Sefiraat
description: 黏液科技附加 黏液工匠 繁體翻譯版.
main: io.github.sefiraat.slimetinker.SlimeTinker
website: https://github.com/Sefiraat/SlimeTinker
version: ${project.version}
api-version: 1.16
depend:
  - Slimefun
softdepend:
  - InfinityExpansion
  - SlimefunWarfare
  - DynaTech
commands:
  slimetinker:
    description: /slimetinker
    usage: /slimetinker <sub>
    aliases: [st, tinker]