blank_issues_enabled: false
contact_links:
  - name: Slimefun Discord Server (for Questions and Suggestions)
    url: https://discord.gg/slimefun
    about: Please ask and answer questions here. (remember, other-addons channel)
  - name: Slimefun Addon Community Discord Server
    url: https://discord.gg/SqD3gg5SAU
    about: You can also ask question here (remember, slime-tinker channel)
